---
image: docker:stable

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:dind

stages:
  - build
  - push

before_script:
  - docker info

build_d10:
  stage: build
  script:
    # https://docs.gitlab.com/ee/ci/variables/predefined_variables.html
    - docker build --rm -t $CI_REGISTRY_USER/$CI_REGISTRY_IMAGE:10 -t $CI_REGISTRY_USER/$CI_REGISTRY_IMAGE:buster .
    - docker run --rm -t $CI_REGISTRY_USER/$CI_REGISTRY_IMAGE:10 lgogdownloader --version

push_to_docker_reg:
 stage: push
 only:
   - master
 script:
   - docker build -f Dockerfile --rm -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:10 -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:buster -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:latest .
   - docker build -f Dockerfile-11 --rm -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:11 -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:bullseye -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:testing .
   - docker build -f Dockerfile-sid --rm -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:sid -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:unstable .
   - docker images
   - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USER" --password-stdin
   - docker push $DOCKERHUB_USER/$DOCKERHUB_PROJECT:10
   - docker push $DOCKERHUB_USER/$DOCKERHUB_PROJECT:buster
   - docker push $DOCKERHUB_USER/$DOCKERHUB_PROJECT:latest
   - docker push $DOCKERHUB_USER/$DOCKERHUB_PROJECT:11
   - docker push $DOCKERHUB_USER/$DOCKERHUB_PROJECT:bullseye
   - docker push $DOCKERHUB_USER/$DOCKERHUB_PROJECT:testing
   - docker push $DOCKERHUB_USER/$DOCKERHUB_PROJECT:sid
   - docker push $DOCKERHUB_USER/$DOCKERHUB_PROJECT:unstable