---
image: docker:stable

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

stages:
  - build
  - push

before_script:
  - docker info
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD

build:
  stage: build
  script:
  # https://docs.gitlab.com/ee/ci/variables/predefined_variables.html
    - docker build -t $CI_REGISTRY_USER/$CI_REGISTRY_IMAGE:latest -t $CI_REGISTRY_USER/$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA .
    - docker run $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA cat /etc/os-release

push:
 stage: push
 only:
   - master
 script:
   - docker build -t $CI_REGISTRY_USER/$CI_REGISTRY_IMAGE:latest -t $CI_REGISTRY_USER/$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA .
   - docker images
   - docker push $CI_REGISTRY_USER/$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
   - docker push $CI_REGISTRY_USER/$CI_REGISTRY_IMAGE:latest