---
image: docker:stable

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:dind

stages:
  - test
  - push

before_script:
  - docker info

test:
  stage: test
  script:
    # https://docs.gitlab.com/ee/ci/variables/predefined_variables.html
    - docker build -f Dockerfile-11 --rm -t lgd:11 .
    - docker build -f Dockerfile-sid --rm -t lgd:sid .
    - docker run --rm -t lgd:11 lgogdownloader --version
    - docker run --rm -t lgd:sid lgogdownloader --version

push_to_docker_reg:
 stage: push
 only:
   - master
 script:
   - docker build -f Dockerfile-11 --rm -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:11 -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:bullseye -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:latest t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:stable .
   - docker build -f Dockerfile-sid --rm -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:sid -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:unstable .
   - docker images
   - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USER" --password-stdin
   - docker push $DOCKERHUB_USER/$DOCKERHUB_PROJECT:11
   - docker push $DOCKERHUB_USER/$DOCKERHUB_PROJECT:latest
   - docker push $DOCKERHUB_USER/$DOCKERHUB_PROJECT:bullseye
   - docker push $DOCKERHUB_USER/$DOCKERHUB_PROJECT:stable
   - docker push $DOCKERHUB_USER/$DOCKERHUB_PROJECT:sid
   - docker push $DOCKERHUB_USER/$DOCKERHUB_PROJECT:unstable