---
#image: qwe1/debdocker:20.10
image: crazymax/docker:latest
services:
  - name: docker:20.10-dind
    command: ["--experimental"]

variables:
  # for some reason docker on gitlab throws context erros with these enabled
  #DOCKER_HOST: tcp://docker:2376
  #DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_DRIVER: overlay2
  #DOCKER_TLS_VERIFY: 1
  DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
  DOCKER_BUILDKIT: 1
  DOCKER_CLI_EXPERIMENTAL: enabled
  #BUILDX_URL: https://github.com/docker/buildx/releases/download/v0.4.1/buildx-v0.4.1.linux-amd64

before_script:
  - mkdir -p $HOME/.docker/cli-plugins/
  - docker buildx version
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - "echo -e '{\n  \"experimental\": \"enabled\"\n}' | tee $HOME/.docker/config.json"
  # https://gitlab.com/richardskumat/playground/-/jobs/2762899800
  - docker context create whatever
  - docker buildx create whatever
  ##
  - docker buildx create --use --driver docker-container --name whatever --platform=linux/amd64,linux/arm/v7,linux/arm64
  - docker buildx inspect --bootstrap whatever
  - docker buildx ls
  - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USER" --password-stdin

stages:
  - test
  - push


test:
  stage: test
  script:
    # https://docs.gitlab.com/ee/ci/variables/predefined_variables.html
    - docker build -f Dockerfile-11 --rm -t lgd:11 .
    - docker build -f Dockerfile-sid --rm -t lgd:sid .
    - docker run --rm -t lgd:11 lgogdownloader --version
    - docker run --rm -t lgd:sid lgogdownloader --version

push_to_docker_reg:
 stage: push
 only:
   - master
 script:
   - docker build -f Dockerfile-11 --rm -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:11 -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:bullseye -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:latest -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:stable .
   - docker build -f Dockerfile-sid --rm -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:sid -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:unstable .
   - docker images
   - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USER" --password-stdin
   - docker push $DOCKERHUB_USER/$DOCKERHUB_PROJECT:11
   - docker push $DOCKERHUB_USER/$DOCKERHUB_PROJECT:latest
   - docker push $DOCKERHUB_USER/$DOCKERHUB_PROJECT:bullseye
   - docker push $DOCKERHUB_USER/$DOCKERHUB_PROJECT:stable
   - docker push $DOCKERHUB_USER/$DOCKERHUB_PROJECT:sid
   - docker push $DOCKERHUB_USER/$DOCKERHUB_PROJECT:unstable