---
services: docker

env:
  global:
    - DOCKER_USER: qwe1
    - DOCKER_IMAGE: lgd
  #matrix:
  #  - whatever

before_script:
  - docker info

script:
  # Run tests.
  - docker build -t $DOCKER_USER/$DOCKER_IMAGE:travis-$DOCKER_FILE .
  - docker images
  - docker run $DOCKER_USER/$DOCKER_IMAGE:travis-$DOCKER_FILE cat /etc/os-release