FROM debian:bullseye
RUN apt-get update && apt-get upgrade -y && apt-get install --no-install-recommends lgogdownloader wget curl -y && \
    rm -rf /var/lib/apt/lists/* && apt-get clean
RUN useradd -m -s /bin/bash user
USER user