FROM debian:sid
RUN apt-get update && apt-get upgrade -y && apt-get install lgogdownloader wget curl -y && \
    rm -rf /var/lib/apt/lists/* && apt-get clean
RUN useradd -m -s /bin/bash user
USER user